### ISSUE TITLE
[tracking] Provide group key derivation at genesis proof

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#394]
Wrapper issue to track
https://github.com/Roasbeef/bips/pull/33

**Comment by halseth** [comment]
It could make sense to divide this into PRs
- [ ] Add versioning https://github.com/lightninglabs/taproot-assets/pull/381
- [ ] Add `asset_genesis` and `asset_group_key_reveal` to proof file (version >= 1)
- [ ] Verify `asset_genesis` and `group_key` at initial mint.
- [ ] Verify asset emission against group key (virtual tx state transition)

**Comment by jharveyb** [comment]
Worth noting we're planning to not actually bump the proof file version, but yes this SGTM.

**Comment by halseth** [comment]
> Verify asset_genesis and group_key at initial mint.

Picking up this one.

**Comment by Roasbeef** [comment]
Needs to be split up into individual issues for the next jaunt.

**Comment by halseth** [comment]
> Verify asset_genesis and group_key at initial mint.

Starting this one

**Comment by guggero** [comment]
> Add asset_genesis and asset_group_key_reveal to proof file (version >= 1)

I'm starting this one. @halseth I hope that's not something you're already working on (tracking issue https://github.com/lightninglabs/taproot-assets/issues/441).

**Comment by halseth** [comment]
@guggero I have started this one: `Verify asset emission against group key (virtual tx state transition)` so make sense for you to take on the proof file 👍

**Comment by jharveyb** [comment]
> @guggero I have started this one:
> 
> > Verify asset emission against group key (virtual tx state transition)
> 
> so make sense for you to take on the proof file 👍

@halseth would that include populating the witness in the minted asset as well? Thinking of which  may not yet have a PR started for implementing them.

**Comment by halseth** [comment]
@jharveyb If you want to make a PR for populating the witness, feel free to do so! This is a starting point I used just for prototyping it: https://github.com/halseth/taproot-assets/commit/7e8506542545b256614d05c8224a363e3f375ab2#diff-cba29164382adad1ea3c845d266d8fb28e183f1a83e2f8940b23f38d1b608e95R511

However I'm travelling this week, so won't have the chance to make it into a proper PR before next week.

**Comment by jharveyb** [comment]
Additional items:

- [ ] Expose methods for issuers to specify the tapscript root via RPC

**Comment by Roasbeef** [comment]
> Verify asset emission against group key (virtual tx state transition)

@jharveyb will make a tracking issue for this

**Comment by jharveyb** [comment]
New tracking issues for last two tasks are #465 and #466 .

**Comment by jharveyb** [comment]
All components are tracked, superceded by #466 and #511 .
