### ISSUE TITLE
BLIP update: RFQ wire messages

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#859]
# TODO
- [x] https://github.com/Roasbeef/blips/pull/4 
# Merged
#845 #683 #792 #778

Cover the RFQ implementations in which some slight updates
@ffranr to enumerate those updates in this issue

**Comment by ffranr** [comment]
The changes I think we should make to RFQ section of the tap BLIP can be found in these reviews that I've left on the tap BLIP PR:

https://github.com/lightning/blips/pull/29#pullrequestreview-1848901112
https://github.com/lightning/blips/pull/29#pullrequestreview-1853954713
https://github.com/lightning/blips/pull/29#pullrequestreview-1856677414
https://github.com/lightning/blips/pull/29#pullrequestreview-1856778322
https://github.com/lightning/blips/pull/29#pullrequestreview-1856784223
https://github.com/lightning/blips/pull/29#pullrequestreview-1856785907

---

### Summary

I'll create a single PR for the following RFQ section modifications:
- [ ] Expiry field should be a Unix timestamp rather than a "number of seconds until expiry".
- [ ] Add optional error code and error message fields to the reject message type.
- [ ] Add directionality field to the request message type.
- [ ] Replace `suggested_rate_tick` field with two fields: asset amount and BTC amount. (Volume matters in a quote.)
- [ ] Other small fixes.

**Comment by ffranr** [comment]
Corresponding PR: https://github.com/Roasbeef/blips/pull/4

**Comment by dstadulis** [comment]
Almost ready
can be pulled out of draft soon
@ffranr will apply some small changes

**Comment by ffranr** [comment]
Roughly, here are the changes we're implementing in this issue:

* Versioning.
* Fixed-point type in-asset to BTC and out-asset to BTC fields.
* A `transfer_type` field in the quote request message.
* Expiry is a unix timestamp in seconds.
* Drop any mention of rate tick. We're using fixed points now.
