### ISSUE TITLE
[tracking]: `lnd/lnwallet` saga

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#898]
Review and ship PRs:
- [x] https://github.com/lightningnetwork/lnd/pull/8622
- [x] https://github.com/lightningnetwork/lnd/pull/8632
- [x] https://github.com/lightningnetwork/lnd/pull/8641
- [x] https://github.com/lightningnetwork/lnd/pull/8771

**Comment by guggero** [comment]
Fixed.
