### ISSUE TITLE
[feature]: RFQ Wire message updates: split `asset_amt`, implicit asset_id types reduction

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#914]
# Background
https://github.com/Roasbeef/blips/pull/3#discussion_r1561808470

# TODO Scope
- [ ] Split the asset_amt field
- [ ] Use only 3 different wire message types (from in situ 5) to handle:
  - [ ] If `in_asset_id` (e.g. USD-X) is only specified
    - [ ] In LN setting, it's a quote for _receiving_ asset_id
  - [ ] If `out_asset_id` is only specified
    - [ ] In LN setting, it's a quote for _sending_ asset_id

Before this change, `asset_amt` was the amount of USD (or w/e) tied to the invoice. So we were asking for a price quote in BTC/asset_id.

# Example user swap flows to confirm wire message reduction
[edit at will]
